const Lead=require('../models/Lead');
const {sendLeadEmail,sendClientConfirmation}=require('../services/emailService');
function requestId(){const d=new Date();const date=d.toISOString().slice(0,10).replaceAll('-','');const rand=Math.floor(1000+Math.random()*9000);return `CCH-${date}-${rand}`}
function xml(v=''){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
exports.create=async(req,res)=>{try{const {clientName,email,phone,companyName,selectedService,selectedServiceId,estimatedBudget,timeline,projectScopeDetails,formData}=req.body;if(!clientName||!email||!projectScopeDetails)return res.status(400).json({success:false,message:'Name, email and project details are required.'});let id=requestId();while(await Lead.exists({requestId:id}))id=requestId();const lead=await Lead.create({requestId:id,clientName,email:email.toLowerCase(),phone,companyName,selectedService,selectedServiceId,estimatedBudget,timeline,projectScopeDetails,formData:formData||{}});try{await sendLeadEmail(lead);lead.emailStatus='sent';lead.emailSentAt=new Date();await lead.save()}catch(e){lead.emailStatus='failed';lead.emailError=e.message;await lead.save()}try{await sendClientConfirmation(lead)}catch(e){}res.status(201).json({success:true,message:'Request received',requestId:lead.requestId,data:lead})}catch(e){console.error(e);res.status(500).json({success:false,message:'Could not submit request'})}};
exports.list=async(req,res)=>{const data=await Lead.find().sort({createdAt:-1}).limit(1000).populate('selectedServiceId','title');res.json({success:true,data})};
exports.get=async(req,res)=>{const data=await Lead.findById(req.params.id).populate('selectedServiceId','title');if(!data)return res.status(404).json({success:false,message:'Lead not found'});res.json({success:true,data})};
exports.update=async(req,res)=>{const allowed=['status','adminNotes'];const update={};allowed.forEach(k=>{if(req.body[k]!==undefined)update[k]=req.body[k]});const data=await Lead.findByIdAndUpdate(req.params.id,update,{new:true,runValidators:true});res.json({success:true,data})};
exports.remove=async(req,res)=>{await Lead.findByIdAndDelete(req.params.id);res.json({success:true})};
exports.exportExcel=async(req,res)=>{const leads=await Lead.find().sort({createdAt:-1}).lean();const headers=['Request ID','Date','Client Name','Email','Phone','Company','Service','Budget','Timeline','Status','Email Status','Project Details','Admin Notes','Custom Form Data'];const rows=[headers,...leads.map(l=>[l.requestId,l.createdAt?new Date(l.createdAt).toISOString():'',l.clientName,l.email,l.phone||'',l.companyName||'',l.selectedService||'',l.estimatedBudget||'',l.timeline||'',l.status,l.emailStatus,l.projectScopeDetails||'',l.adminNotes||'',JSON.stringify(l.formData||{})])];const sheetRows=rows.map(row=>`<Row>${row.map(v=>`<Cell><Data ss:Type="String">${xml(v)}</Data></Cell>`).join('')}</Row>`).join('');const xls=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="CoffeeCODEHub Leads"><Table>${sheetRows}</Table></Worksheet></Workbook>`;res.setHeader('Content-Type','application/vnd.ms-excel');res.setHeader('Content-Disposition',`attachment; filename="coffeecodehub-leads-${new Date().toISOString().slice(0,10)}.xls"`);res.send(xls)};
