const bcrypt=require('bcryptjs');const fs=require('fs');const path=require('path');const {v2:cloudinary}=require('cloudinary');const Admin=require('../models/Admin'),Service=require('../models/Service'),Project=require('../models/Project'),Site=require('../models/SiteSettings'),Home=require('../models/Homepage'),Blog=require('../models/Blog');
const services=[['Web Development','web-development','Fast, responsive and conversion-focused websites and web applications.'],['Software Development','software-development','Custom business software built around your real workflows.'],['Mobile App Development','mobile-app-development','Cross-platform mobile apps with polished UX and reliable backends.'],['UI/UX Design','ui-ux-design','Clear product experiences that look premium and are easy to use.'],['WordPress Development','wordpress-development','Professional WordPress websites that are easy to manage and grow.'],['E-commerce Development','ecommerce-development','Online stores designed to turn browsing into measurable sales.'],['Digital Marketing','digital-marketing','Content and campaigns designed around measurable business goals.'],['Branding & Strategy','branding-strategy','A coherent visual identity and digital positioning for your business.']];
exports.seed=async()=>{if(process.env.SEED_DEFAULTS!=='true')return;const adminEmail=process.env.ADMIN_EMAIL.toLowerCase();const existing=await Admin.findOne({email:adminEmail});if(!existing){const password=process.env.ADMIN_PASSWORD;await Admin.create({name:'CoffeeCODEHub Admin',email:adminEmail,passwordHash:await bcrypt.hash(password,12),role:'admin'});console.log(`Seeded admin: ${adminEmail}`)}for(const [title,slug,shortDescription] of services){const i=services.findIndex(x=>x[1]===slug);const defaults={title,slug,shortDescription,fullDescription:`${shortDescription} CoffeeCODEHub combines strategy, design and engineering to deliver practical digital solutions.`,category:'IT Services',iconIdentifier:['globe','code','mobile','palette','globe','cart','bullhorn','rocket'][i],keyFeatures:['Responsive experience','Business-focused implementation','Maintainable architecture','Clear delivery milestones'],technologies:['React','Node.js','MongoDB'],deliverables:['Responsive production-ready experience','Clean maintainable implementation','Deployment-ready handover','Post-launch improvement path'],process:[{title:'Discover',description:'Understand goals, users, scope and priorities',displayOrder:0},{title:'Plan',description:'Define milestones, architecture and delivery plan',displayOrder:1},{title:'Build',description:'Design and develop the agreed solution',displayOrder:2},{title:'Test & Launch',description:'Validate, optimize and prepare the release',displayOrder:3}],faq:[{question:'How does a project start?',answer:'Submit the service request with your requirements. CoffeeCODEHub reviews the brief and contacts you for the next discussion.'},{question:'Can the scope change later?',answer:'Yes. Scope changes are reviewed with the team and reflected in the project plan before implementation.'}],formFields:[{fieldId:'scope',label:'Project requirements',name:'projectRequirements',type:'textarea',required:true,placeholder:'Tell us what you need to build.'}]};let existing=await Service.findOne({slug});if(!existing)await Service.create({...defaults,displayOrder:i,isActive:true,isFeatured:i<6});else{const patch={};for(const k of ['fullDescription','category','iconIdentifier','keyFeatures','technologies','deliverables','process','faq','formFields'])if(existing[k]===undefined||existing[k]===null||(Array.isArray(existing[k])&&existing[k].length===0))patch[k]=defaults[k];if(Object.keys(patch).length)await Service.updateOne({_id:existing._id},{$set:patch});}}const projects=[
 {title:'Library Management System',slug:'library-management-system',category:'Software',shortDescription:'A structured management solution focused on records, workflows and usability.',techStack:['C++'],isFeatured:true,isPublished:true,displayOrder:0},
 {title:'Smart Home Management',slug:'smart-home-management',category:'IoT / Software',shortDescription:'An interactive smart-home control concept for connected environments.',techStack:['Java'],isFeatured:true,isPublished:true,displayOrder:1},
 {title:'E-commerce Platform',slug:'ecommerce-platform',category:'Web Development',shortDescription:'A storefront experience with shopping, product and checkout flows.',techStack:['HTML','CSS','JavaScript'],isFeatured:true,isPublished:true,displayOrder:2},
 {title:'Fitness Tracker App',slug:'fitness-tracker-app',category:'Mobile / Web',shortDescription:'A modern interface concept for tracking activity and progress.',techStack:['React'],isFeatured:true,isPublished:true,displayOrder:3},
 {title:'Educational Platform',slug:'educational-platform',category:'EdTech',shortDescription:'An LMS-style experience for courses, quizzes and learning content.',techStack:['WordPress'],isFeatured:false,isPublished:true,displayOrder:4},
 {title:'Business Branding',slug:'business-branding',category:'Branding',shortDescription:'A cohesive identity direction for a modern digital-first business.',techStack:['Figma'],isFeatured:false,isPublished:true,displayOrder:5}
];
const assetDir=path.join(__dirname,'..','..','frontend','src','assets');const uploadDir=path.join(__dirname,'..','uploads');fs.mkdirSync(uploadDir,{recursive:true});
const cloudinaryReady=Boolean(process.env.CLOUDINARY_CLOUD_NAME&&process.env.CLOUDINARY_API_KEY&&process.env.CLOUDINARY_API_SECRET);
if(cloudinaryReady)cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});
async function seedImageUrl(source,index){
  if(!fs.existsSync(source))return '';
  if(cloudinaryReady){
    const result=await cloudinary.uploader.upload(source,{folder:'coffeecodehub/projects',public_id:`seed-project-${index}`,resource_type:'image',overwrite:true});
    return result.secure_url;
  }
  const dest=path.join(uploadDir,`seed-project-${index}.png`);
  if(!fs.existsSync(dest))fs.copyFileSync(source,dest);
  return `${(process.env.API_PUBLIC_URL||process.env.RENDER_EXTERNAL_URL||`http://localhost:${process.env.PORT||5000}`).replace(/\/$/,'')}/uploads/seed-project-${index}.png`;
}
for(let i=0;i<projects.length;i++){const project=projects[i];const existingProject=await Project.findOne({slug:project.slug});const source=path.join(assetDir,`pic${i+1}.png`);if(!existingProject){const coverImage=await seedImageUrl(source,i+1);await Project.create({...project,coverImage,fullDescription:project.shortDescription,caseStudy:`Project overview\n\n${project.shortDescription}\n\nCoffeeCODEHub project record. Add the complete client-approved case study from the Admin Panel.`});}else if(cloudinaryReady && /localhost|127\.0\.0\.1|\/uploads\//i.test(String(existingProject.coverImage||''))){const coverImage=await seedImageUrl(source,i+1);if(coverImage)await Project.updateOne({_id:existingProject._id},{$set:{coverImage}});}}
if(!await Site.findOne({key:'global'}))await Site.create({key:'global',companyName:'CoffeeCODEHub',tagline:'Digital products & IT services',email:'coffeecodehub@gmail.com',phone:'0311 4909975',whatsapp:'923114909975',defaultSeoTitle:'CoffeeCODEHub | Web Development & IT Services',defaultSeoDescription:'CoffeeCODEHub builds modern websites, software, mobile apps, e-commerce platforms, UI/UX experiences and digital solutions for businesses.',footerDescription:'Modern web, software, mobile, design and digital solutions for businesses.',socialLinks:{facebook:'',instagram:'',linkedin:'',twitter:'',github:'',tiktok:'',youtube:'',whatsapp:'',telegram:'',discord:'',pinterest:'',threads:'',snapchat:'',reddit:''},navigation:[{label:'Home',path:'/',displayOrder:0},{label:'About',path:'/about',displayOrder:1},{label:'Services',path:'/services',displayOrder:2},{label:'Projects',path:'/projects',displayOrder:3},{label:'Blog',path:'/blog',displayOrder:4},{label:'Team',path:'/team',displayOrder:5},{label:'Contact',path:'/contact',displayOrder:6}]});const siteDoc=await Site.findOne({key:'global'});
if(siteDoc){
  const links=Array.isArray(siteDoc.navigation)?[...siteDoc.navigation]:[];
  if(!links.some(x=>x.path==='/review')) links.push({label:'Reviews',path:'/review',displayOrder:links.length});
  siteDoc.navigation=links;
  siteDoc.socialLinks={...(siteDoc.socialLinks||{}),threads:siteDoc.socialLinks?.threads||'',snapchat:siteDoc.socialLinks?.snapchat||'',reddit:siteDoc.socialLinks?.reddit||''};
  await siteDoc.save();
}
if(!await Home.findOne({key:'home'}))await Home.create({key:'home',hero:{title:'We build digital products that move businesses forward.',description:'From business websites and custom software to mobile apps, e-commerce and UI/UX — CoffeeCODEHub turns business requirements into reliable digital experiences.',primaryCta:'Start Your Project',secondaryCta:'Explore Our Work'},stats:[{label:'Core Services',value:'8'},{label:'Full-Stack',value:'MERN'},{label:'SEO Foundation',value:'Built-in'},{label:'Client-first',value:'Always'}]});if(!await Blog.countDocuments())await Blog.insertMany([{title:'How to Choose a Web Development Company for Your Business',slug:'how-to-choose-a-web-development-company',excerpt:'A practical guide to evaluating technical capability, communication, scope and long-term fit.',content:'Choosing a development partner starts with the problem you need solved. Compare portfolio evidence, technical communication, scope clarity, maintenance approach and how the team handles change. Avoid choosing purely on the lowest quote: unclear scope often becomes expensive later.',category:'Web Development',author:'CoffeeCODEHub',readingTime:'6 min read',status:'published',publishedAt:new Date()},{title:'Why Website Performance Matters for Search and Conversion',slug:'website-performance-and-seo',excerpt:'Performance affects usability, discoverability and business outcomes.',content:'A fast website is easier to use and gives search engines a cleaner experience. Focus on efficient images, sensible JavaScript, stable layouts and fast server responses. Measure before and after changes rather than chasing arbitrary scores.',category:'SEO',author:'CoffeeCODEHub',readingTime:'5 min read',status:'published',publishedAt:new Date()}]);};
