import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FiArrowRight, FiCheck, FiCode, FiLayers, FiSmartphone, FiPenTool, FiTrendingUp, FiMonitor, FiDatabase, FiShoppingCart, FiBarChart2, FiCpu, FiExternalLink, FiX } from 'react-icons/fi';
import bgVideo from './assets/bg-video.mp4';
import { mediaUrl } from './lib/media';
import SEO from './components/SEO';
import SectionTitle from './components/SectionTitle';
import ServiceRequestModal from './components/ServiceRequestModal';
import { api } from './lib/api';
import { fallbackServices, fallbackProjects } from './lib/data';import {useSite} from './context/useSite';

const iconMap={globe:FiMonitor,code:FiCode,mobile:FiSmartphone,palette:FiPenTool,cart:FiShoppingCart,bullhorn:FiBarChart2,marketing:FiBarChart2,rocket:FiCpu,database:FiDatabase,monitor:FiMonitor,server:FiMonitor,cloud:FiMonitor,shield:FiCheck,camera:FiPenTool,layers:FiLayers,trending:FiTrendingUp,briefcase:FiLayers,zap:FiCpu};
export default function Home(){const {home}=useSite();const [services,setServices]=useState(null);const [projects,setProjects]=useState(null);const [selected,setSelected]=useState(null);const [reviews,setReviews]=useState([]);const [proof,setProof]=useState(null);useEffect(()=>{Promise.allSettled([api('/services?active=true'),api('/projects?featured=true'),api('/reviews')]).then(([s,p,r])=>{if(s.status==='fulfilled'&&Array.isArray(s.value.data)&&s.value.data.length)setServices(s.value.data);else setServices(fallbackServices);if(p.status==='fulfilled'&&Array.isArray(p.value.data)&&p.value.data.length)setProjects(p.value.data);else setProjects(fallbackProjects);if(r.status==='fulfilled')setReviews(r.value.data||[])})},[]);if(!services||!projects)return <main className="pt-20 min-h-screen bg-white" aria-busy="true"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-24"><div className="h-8 w-48 rounded-xl bg-slate-100 animate-pulse"/><div className="mt-6 h-16 max-w-3xl rounded-2xl bg-slate-100 animate-pulse"/><div className="mt-4 h-5 max-w-2xl rounded-xl bg-slate-100 animate-pulse"/></div></main>;return <><SEO title="Web Development & IT Services Company" description="CoffeeCODEHub builds high-performance websites, web applications, mobile apps, UI/UX designs, e-commerce platforms and digital solutions for businesses." path="/"/>
<section className="relative min-h-[760px] overflow-hidden bg-slate-950 flex items-center pt-20"><video autoPlay loop muted playsInline poster={mediaUrl(home.hero?.image) || undefined} className="absolute inset-0 w-full h-full object-cover opacity-50"><source src={bgVideo} type="video/mp4"/></video>{home.hero?.image&&<img src={mediaUrl(home.hero.image)} alt="CoffeeCODEHub digital technology" className="absolute inset-0 w-full h-full object-cover opacity-20 mix-blend-screen"/>}<div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/90 to-slate-950/45"/><div className="absolute -top-32 right-0 h-96 w-96 rounded-full bg-[#F59E0B]/15 blur-3xl"/><div className="relative z-10 max-w-7xl mx-auto px-5 lg:px-8 w-full py-24"><div className="max-w-4xl"><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-bold tracking-[.2em] text-amber-300">COFFECODEHUB • DIGITAL PRODUCTS & IT SERVICES</motion.p><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.1}} className="mt-7 text-5xl md:text-7xl font-black leading-[1.02] tracking-tight text-white">{home.hero?.title||<>We build digital products that <span className="text-[#F59E0B]">move businesses forward.</span></>}</motion.h1><p className="mt-7 max-w-2xl text-lg md:text-xl leading-8 text-slate-300">{home.hero?.description||'From business websites and custom software to mobile apps, e-commerce and UI/UX — CoffeeCODEHub turns business requirements into reliable digital experiences.'}</p><div className="mt-9 flex flex-wrap gap-4"><Link to="/contact" className="inline-flex items-center gap-2 rounded-xl bg-[#F59E0B] px-7 py-4 font-black text-slate-950 hover:bg-amber-400">Start Your Project <FiArrowRight/></Link><Link to="/projects" className="inline-flex items-center gap-2 rounded-xl border border-white/25 bg-white/5 px-7 py-4 font-bold text-white hover:bg-white hover:text-slate-950">Explore Our Work</Link></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 text-sm text-slate-300"><span className="flex items-center gap-2"><FiCheck className="text-[#F59E0B]"/> Business-focused solutions</span><span className="flex items-center gap-2"><FiCheck className="text-[#F59E0B]"/> Modern technology</span><span className="flex items-center gap-2"><FiCheck className="text-[#F59E0B]"/> Clear communication</span></div></div></div></section>
<section className="border-b bg-white"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-8 grid grid-cols-2 md:grid-cols-4 gap-6 text-center">{(home.stats?.length?home.stats:[{label:'Core Services',value:String(services.length)},{label:'Featured Projects',value:String(projects.length)},{label:'Technology Stack',value:'MERN'},{label:'Client-first process',value:'100%'}]).slice(0,4).map(x=><div key={x.label}><b className="text-3xl font-black text-[#F59E0B]">{x.value}</b><p className="text-sm text-slate-500 mt-1">{x.label}</p></div>)}</div></section>
<section className="py-24 bg-white"><div className="max-w-7xl mx-auto px-5 lg:px-8"><SectionTitle eyebrow="What we do" title="Technology, design and growth under one roof." text="Choose the service you need. Every service has its own project-request flow so we can collect requirements that actually matter."/><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">{services.slice(0,8).map(s=>{const Icon=iconMap[s.iconIdentifier]||FiCode;return <article key={s._id||s.slug} className="group rounded-3xl border border-slate-200 bg-white p-6 hover:-translate-y-1 hover:border-amber-300 hover:shadow-xl transition"><div className="relative w-14 h-14 rounded-2xl bg-slate-950 text-[#F59E0B] flex items-center justify-center text-2xl shadow-lg shadow-amber-100 group-hover:rotate-2 group-hover:scale-105 transition"><span className="absolute inset-0 rounded-2xl ring-1 ring-amber-400/20"/><Icon/></div><h3 className="mt-5 text-xl font-black">{s.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{s.shortDescription}</p><button onClick={()=>setSelected(s)} className="mt-5 text-sm font-black text-[#b77900] inline-flex items-center gap-2">Request this service <FiArrowRight/></button></article>})}</div><div className="text-center mt-10"><Link to="/services" className="font-black text-[#b77900]">View all services →</Link></div></div></section>
<section className="py-24 bg-slate-50"><div className="max-w-7xl mx-auto px-5 lg:px-8"><SectionTitle eyebrow="Selected work" title="Projects that show what we can build." text="Explore case studies, technologies and the thinking behind our work."/><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{projects.slice(0,6).map(p=><Link to={`/project/${p.slug}`} key={p._id||p.slug} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="aspect-[16/10] overflow-hidden bg-slate-200"><img src={mediaUrl(p.coverImage||p.image)} alt={p.title} className="w-full h-full object-cover group-hover:scale-105 transition duration-500"/></div><div className="p-6"><p className="text-xs uppercase tracking-widest font-bold text-[#F59E0B]">{p.category}</p><h3 className="mt-2 text-xl font-black">{p.title}</h3><p className="mt-2 text-sm text-slate-600">{p.shortDescription||p.desc}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-black">View case study <FiArrowRight/></span></div></Link>)}</div></div></section>
<section className="py-24 bg-slate-950 text-white"><div className="max-w-6xl mx-auto px-5 lg:px-8"><SectionTitle dark eyebrow="Our process" title="A straightforward path from idea to launch." text="Clear milestones keep projects understandable for business owners and delivery teams."/><div className="grid md:grid-cols-3 lg:grid-cols-6 gap-4">{['Discover','Plan','Design','Develop','Test','Launch'].map((x,i)=><div key={x} className="rounded-2xl border border-white/10 bg-white/5 p-5"><span className="text-xs font-black text-[#F59E0B]">0{i+1}</span><h3 className="mt-8 font-black">{x}</h3></div>)}</div></div></section>
<section className="py-24 bg-white"><div className="max-w-7xl mx-auto px-5 lg:px-8"><SectionTitle eyebrow="Client voice" title="What our clients say" text="Genuine client feedback shared directly through CoffeeCODEHub is shown here."/><div className="mt-6 flex justify-end"><Link to="/review" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-5 py-3 text-sm font-black hover:border-amber-300">Share your experience <FiArrowRight/></Link></div>{reviews.length? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{reviews.slice(0,6).map(r=><article key={r._id} className="rounded-3xl border p-6"><div className="text-[#F59E0B] tracking-widest">{'★'.repeat(r.rating||5)}</div><p className="mt-4 text-slate-700 leading-7">“{r.feedbackText}”</p>{r.proofScreenshots?.length>0&&<button type="button" onClick={()=>setProof(mediaUrl(r.proofScreenshots[0]))} className="mt-4 text-sm font-bold text-[#b77900]">View project proof ↗</button>}<div className="mt-6 flex items-end justify-between gap-4"><div><b>{r.clientName}</b><p className="text-sm text-slate-500">{r.companyName||'Client'}</p></div><div className="flex items-center gap-3">{r.projectLink&&<a href={r.projectLink} target="_blank" rel="noreferrer" className="text-sm font-bold text-[#b77900] inline-flex items-center gap-1">View project <FiExternalLink/></a>}{r.clientWebsiteUrl&&<a href={r.clientWebsiteUrl} target="_blank" rel="noreferrer" className="text-sm font-bold text-[#b77900] inline-flex items-center gap-1">Client website <FiExternalLink/></a>}</div></div></article>)}</div>:<div className="rounded-3xl border border-dashed p-10 text-center text-slate-500">Client reviews will appear here as soon as clients share their experience.</div>}</div></section>
<section className="py-24 bg-[#F59E0B]"><div className="max-w-5xl mx-auto px-5 text-center"><p className="text-sm font-black tracking-widest uppercase">Have a project in mind?</p><h2 className="mt-3 text-4xl md:text-6xl font-black text-slate-950">Let’s turn the requirement into something real.</h2><Link to="/contact" className="mt-8 inline-flex rounded-xl bg-slate-950 text-white px-7 py-4 font-black">Start Your Project <FiArrowRight className="ml-2"/></Link></div></section>
{selected&&<ServiceRequestModal service={selected} onClose={()=>setSelected(null)}/>} {proof&&<div className="fixed inset-0 z-[120] bg-slate-950/80 backdrop-blur-sm p-5 flex items-center justify-center" onClick={()=>setProof(null)}><div className="relative max-w-5xl max-h-[90vh]"><button className="absolute -right-3 -top-3 z-10 w-10 h-10 rounded-full bg-white flex items-center justify-center" onClick={()=>setProof(null)}><FiX/></button><img src={mediaUrl(proof)} alt="Client project proof" className="max-h-[88vh] max-w-full rounded-2xl shadow-2xl"/></div></div>}</>}
