import pic1 from '../assets/pic1.png';
import pic2 from '../assets/pic2.png';
import pic3 from '../assets/pic3.png';
import pic4 from '../assets/pic4.png';
import pic5 from '../assets/pic5.png';
import pic6 from '../assets/pic6.png';
export const fallbackServices = [
 { _id:'web', slug:'web-development', title:'Web Development', shortDescription:'Fast, responsive and conversion-focused websites and web applications.', fullDescription:'We design and develop modern websites and web applications for startups, service businesses and growing companies.', iconIdentifier:'globe', category:'Development', keyFeatures:['Responsive UI','SEO-ready architecture','CMS & API integrations','Performance optimization'], technologies:['React','Node.js','MongoDB','Next.js'] },
 { _id:'software', slug:'software-development', title:'Software Development', shortDescription:'Custom business software built around your real workflows.', fullDescription:'Custom dashboards, portals, internal tools and scalable software that reduce manual work and improve operations.', iconIdentifier:'code', category:'Development', keyFeatures:['Custom workflows','Role-based access','REST APIs','Scalable architecture'], technologies:['MERN','Node.js','Express','MongoDB'] },
 { _id:'mobile', slug:'mobile-app-development', title:'Mobile App Development', shortDescription:'Cross-platform mobile apps with polished UX and reliable backends.', fullDescription:'Production-ready mobile experiences for Android and iOS with APIs, authentication and scalable backend services.', iconIdentifier:'mobile', category:'Development', keyFeatures:['Android & iOS','API integration','Authentication','Push-ready architecture'], technologies:['React Native','Node.js','MongoDB'] },
 { _id:'uiux', slug:'ui-ux-design', title:'UI/UX Design', shortDescription:'Clear product experiences that look premium and are easy to use.', fullDescription:'Research-informed interface design, prototypes and design systems that help products communicate clearly.', iconIdentifier:'palette', category:'Design', keyFeatures:['Wireframes','High-fidelity UI','Design systems','Prototyping'], technologies:['Figma','FigJam'] },
 { _id:'wordpress', slug:'wordpress-development', title:'WordPress Development', shortDescription:'Professional WordPress websites that are easy to manage and grow.', fullDescription:'Business websites, landing pages and custom WordPress builds with clean structure, speed and on-page SEO foundations.', iconIdentifier:'globe', category:'Development', keyFeatures:['Custom pages','CMS setup','SEO foundations','Speed optimization'], technologies:['WordPress','PHP','Elementor'] },
 { _id:'ecommerce', slug:'ecommerce-development', title:'E-commerce Development', shortDescription:'Online stores designed to turn browsing into measurable sales.', fullDescription:'Conversion-focused storefronts with product catalogs, checkout flows, integrations and admin workflows.', iconIdentifier:'cart', category:'Commerce', keyFeatures:['Product catalog','Checkout flow','Payments integration','Order management'], technologies:['React','Node.js','MongoDB'] },
 { _id:'marketing', slug:'digital-marketing', title:'Digital Marketing', shortDescription:'Content and campaigns designed around measurable business goals.', fullDescription:'Search, social and content strategies that connect your brand with the people actively looking for your services.', iconIdentifier:'bullhorn', category:'Growth', keyFeatures:['Content strategy','Social campaigns','SEO content','Analytics'], technologies:['SEO','Meta Ads','Analytics'] },
 { _id:'branding', slug:'branding-strategy', title:'Branding & Strategy', shortDescription:'A coherent visual identity and digital positioning for your business.', fullDescription:'Brand identity, messaging and digital direction that make your business easier to recognize and trust.', iconIdentifier:'rocket', category:'Brand', keyFeatures:['Brand direction','Visual identity','Messaging','Digital guidelines'], technologies:['Figma','Adobe'] },
];

export const fallbackProjects = [
 { _id:'p1', slug:'library-management-system', title:'Library Management System', category:'Software', shortDescription:'A structured management solution focused on records, workflows and usability.', coverImage:pic1, techStack:['C++'], isFeatured:true },
 { _id:'p2', slug:'smart-home-management', title:'Smart Home Management', category:'IoT / Software', shortDescription:'An interactive smart-home control concept for connected environments.', coverImage:pic2, techStack:['Java'], isFeatured:true },
 { _id:'p3', slug:'ecommerce-platform', title:'E-commerce Platform', category:'Web Development', shortDescription:'A storefront experience with shopping, product and checkout flows.', coverImage:pic3, techStack:['HTML','CSS','JavaScript'], isFeatured:true },
 { _id:'p4', slug:'fitness-tracker-app', title:'Fitness Tracker App', category:'Mobile / Web', shortDescription:'A modern interface concept for tracking activity and progress.', coverImage:pic4, techStack:['React'], isFeatured:true },
 { _id:'p5', slug:'educational-platform', title:'Educational Platform', category:'EdTech', shortDescription:'An LMS-style experience for courses, quizzes and learning content.', coverImage:pic5, techStack:['WordPress'], isFeatured:false },
 { _id:'p6', slug:'business-branding', title:'Business Branding', category:'Branding', shortDescription:'A cohesive identity direction for a modern digital-first business.', coverImage:pic6, techStack:['Figma'], isFeatured:false },
];
